### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#35]
The news page probably ought to inherit from routable page mixin, http://docs.wagtail.io/en/v1.6.3/reference/contrib/routablepage.html, and news articles that are regular models http://docs.wagtail.io/en/v1.6.3/reference/contrib/modeladmin.html 
This would enforce that all news articles exist under that news page.

**Comment by 545zhou** [comment]
Do we really want to make news article a regular model? I think it's more intuitive to create an article page under the index page. In the official demo, blog is very similar to the concept of article here. https://github.com/torchbox/wagtaildemo/blob/master/demo/models.py. I also added some limitations to the article pages so that they can only be attached under the article index page.

**Comment by NyanHelsing** [comment]
they can be both; theyre not mutually exclusive

**Comment by NyanHelsing** [comment]
right now there aren't really tools to search and sort article; like we can with people. Is there a way to do that if theyre only pages?

**Comment by 545zhou** [comment]
Pages could be registered as modeladmin. I've done the coding.
![image](https://cloud.githubusercontent.com/assets/4791500/19168503/603c807c-8bde-11e6-8a26-49719d04d1c5.png)
