### ISSUE TITLE
tabs block is fragile

### ISSUE THREAD

**Issue by NyanHelsing** [HalcyonChimera/cos.io#81]
js needs to be reworked/ reordering of tabs. delete the tab when the struct is deleted.

**Comment by atelic** [comment]
Looks like a lot of work has been done on this (d0c53f1, 72a68bf, 47b0207, etc). What else is needed?

**Comment by atelic** [comment]
# Audit

## Done
- The Admin side looks really good on this
- Tabs are functional though they look like just a `<p>` tag:
  ![screen shot 2016-10-17 at 12 24 09 pm](https://cloud.githubusercontent.com/assets/8905795/19445980/abd731d8-9464-11e6-8757-1644dd15df6b.png)

## Issues:
- It seems like [`tab_style`](https://github.com/HalcyonChimera/cos.io/blob/47b02077f72f80e840d9d055d4e6b24615070dbc/common/templates/common/blocks/tabbed_block.html#L87) never gets set. Adding it in Dev Tools looks a lot better:

![screen shot 2016-10-17 at 12 25 40 pm](https://cloud.githubusercontent.com/assets/8905795/19446033/fac40758-9464-11e6-825d-80f3a1378b62.png)
- `vertical-tabs` and `horizontal-tabs` display the same way (because they're implemented the same way [here](https://github.com/HalcyonChimera/cos.io/blob/develop/common/templates/common/blocks/tabbed_block.html#L7-L48)). As in the above screenshot. 
- The old `TabIndex` code and template still exist. Those should be removed.

**Comment by atelic** [comment]
Looks like these were addressed in 05db89b and friends. Closing
